export const STRINGS = {
    en: {
        labels: {
            format: 'Format',
            clear_filters: 'Clear Filters',
            invalid_value: 'Invalid value',
            search: 'Search',
            are_you_sure: 'Are you sure?',
            delete: 'Delete',
            share: 'Share',
            locate: 'Locate',
            or: 'OR',
            check_email: 'Check your email',
            enter_password: 'Please enter password for verification',
            code_was_sent: 'A code was sent for verification',
            account_exists: 'Account already exists',
            login_with_email: 'Login With Email',
            passwordless_teaser: 'We will send you a code to your inbox',
            enter_code: 'Enter code',
            send: 'Send',
            all: 'All',
            incomplete: 'Incomplete',
            has_errors: 'Error',
            wrong_range: 'Range Invalid',
            invalid_entries: 'Invalid Entries',
            add_branch: 'Add Branch',
            status: 'Status',
            from: 'From',
            to: 'To',
            reset: 'Reset',
            show: 'Show',
            show_filters: 'Show filters on entries list',
            hide_filters: 'Hide filters',
            filters: 'Filters',
            filter_by_title: 'Filter by title',
            no_hits_found: 'Nothing found',
            not_available: 'Not available',
            name: 'Name',
            description: 'Description',
            small_description: 'Small Description',
            homepage: 'Homepage',
            project_info: 'Project Info',
            version: 'Version',
            advanced_settings: 'Advanced',
            ok: 'Ok',
            download_remote_entries: 'Download remote entries',
            remote_entry: 'Remote entry',
            download_warning: 'This will remove any remote entries you already have for this project on your device. Continue?',
            text_size: 'Text size',
            accessibility: 'Accessibility',
            type_answer_here: 'Type answer here...',
            confirm_answer_here: 'Confirm answer here...',
            confirm: 'Confirm',
            help: 'Help',
            user_guide: 'User Guide',
            hi: 'Hi',
            prev: 'Prev',
            next: 'Next',
            quit: 'Quit',
            save: 'Save',
            save_entry: 'Save entry',
            quit_entry: 'Quit',
            save_branch_entry: 'Save branch',
            quit_branch: 'Quit',
            login: 'Login',
            logout: 'Logout',
            scan: 'Scan',
            entries: 'entries',
            branch_entries: 'Branch entries',
            update_location: 'Update location',
            not_located_yet: 'Not set yet',
            latitude: 'Latitude',
            longitude: 'Longitude',
            accuracy: 'Accuracy',
            unknown_error: 'Unknown error',
            db_created: 'Epicollect5 database ready',
            db_not_created: 'Error creating Epicollect5 database!',
            locating: 'Locating',
            wait: 'Please Wait...',
            saving: 'Saving...',
            loading: 'Loading...',
            acquiring_position: 'Acquiring position',
            location_acquired: 'Location acquired',
            location_fail: 'Not able to locate!',
            location_service_fail: 'Location Services and Permissions must both be enabled for Epicollect5 to get the device location.',
            ios_location_permission_denied: 'Epicollect5 location permission was denied, please enable it in Settings',
            ios_location_permission_restricted: 'Epicollect5 location permission is restricted for the current user',
            android_location_permission_denied_always: 'Epicollect5 location permission is denied, please grant it. It is not possible to use Location Services without appropriate permission',
            no_projects_found: 'No projects found',
            date_selected_is: 'The date selected is: ',
            time_selected_is: 'The time selected is: ',
            preparing_scanner: 'Preparing scanner',
            failed_because: 'Failed because: ',
            stop: 'Stop',
            play: 'Play',
            record: 'Record',
            recording: 'Recording',
            playing: 'Playing',
            recording_audio: 'Recording audio...',
            playing_audio: 'Playing audio...',
            shoot: 'Shoot',
            video_saved: 'Video saved',
            audio_saved: 'Audio saved',
            cannot_save_file: 'Cannot save the file! Please retry',
            file_available: 'File available',
            uploading_entries: 'Uploading Entries',
            loading_project: 'Loading project',
            loading_entries: 'Loading entries',
            loading_entry: 'Loading entry',
            no_entries_found: 'No entries found',
            no_errors_found: 'No errors found',
            pick_possible_answer: 'Pick possible answer',
            permission_denied: 'Permission denied',
            location_not_available: 'Location is not available, Epicollect5 will not be able to locate you.',
            min: 'Min',
            max: 'Max',
            no_answer_given: 'No answer given ',
            error: 'Error',
            delete_project: 'Delete Project',
            delete_entry: 'Delete Entry',
            delete_all_entries: 'Delete All Entries',
            delete_synced_entries: 'Delete Synced Entries',
            delete_unsynced_entries: 'Delete Unsynced Entries',
            bookmark: 'Bookmark',
            bookmark_title: 'Add a bookmark title',
            close: 'Close',
            add_bookmark: 'Add Bookmark',
            add_entry: 'Add Entry',
            type_hint: 'Type here',
            menu: 'Menu',
            project_options: 'Project Options',
            upload_entries: 'Upload Entries',
            download_entries: 'Download Entries',
            unsync_all_entries: 'Unsync All Entries',
            export_all_entries: 'Export All Entries',
            unsynced: 'Unsynced',
            unsync_entry: 'Unsync Entry',
            bookmark_page: 'Bookmark Page',
            remove_bookmark: 'Remove Bookmark',
            sort: 'Sort',
            newest: 'Newest',
            oldest: 'Oldest',
            sign_in: 'Signing in',
            no_bookmarks_found: 'No bookmarks found',
            my_bookmarks: 'My Bookmarks',
            export_entries: 'Export json entries',
            exporting: 'Exporting',
            exporting_success: 'All Entries Exported!',
            exported_to: 'Exported to: ',
            deleting_project: 'Deleting Project',
            deleting_entries: 'Deleting Entries',
            entry_deleted: 'Entry Deleted',
            file_deleted: 'File Deleted',
            email: 'Email',
            password: 'Password',
            ldap_username: 'Ldap Username',
            ldap_password: 'Ldap Password',
            google_sign_in: 'Google Sign In',
            upload_data: 'Upload data',
            upload_photos: 'Upload photos',
            upload_videos: 'Upload videos',
            upload_audios: 'Upload audio',
            uploading_photos: 'Uploading photos',
            uploading_videos: 'Uploading videos',
            uploading_audios: 'Uploading audio',
            all_entries_uploaded: 'All Entries Uploaded',
            entries_errors: 'Some of the entries have errors',
            children: 'Children',
            search_for_project: 'Search for a project',
            add_project: 'Add Project',
            projects: 'Projects',
            delete_branch_entry: 'Delete Branch Entry',
            back: 'Back',
            settings: 'Settings',
            server_url: 'Server Url',
            server_url_placeholder: 'eg http://www.mydomain.com',
            downloads: 'Downloads',
            download: 'Download',
            warning: 'Warning',
            missing_permission: 'You must grant the appropriate permission to perform this action',
            please_wait: 'Please Wait...',
            server_url_error: 'Server not found, please check your server URL in the settings',
            quitting: 'Quitting',
            cancel: 'Cancel',
            project_outdated: 'Form has been updated.',
            update_project: 'Update form on your device?',
            project_updated: 'Forms updated.',
            updating_project: 'Updating Forms.',
            updating_entries: 'Updating entries.',
            check_for_updates: 'Check for Form Updates',
            checking_for_updates: 'Checking for updates...',
            loading_projects: 'Loading Projects',
            incomplete_entry: 'This entry is incomplete',
            unsynced_entries: 'Unsynced entries',
            unsynced_entry: 'Entry unsynced.',
            sync_now: 'Upload',
            save_entry_and_sync: 'Save entry and Sync',
            check_entries: 'Check entries',
            connect_to_internet_to_upload: 'Please connect to the internet to upload entries.',
            entries_errors_page: 'Entries with Errors',
            check_entries_below: 'Check the entries below for errors.',
            branch: 'Branch',
            pattern: 'Pattern',
            required: '* This field is required',
            entries_media_errors: 'Could not upload your media. Please try again later.',
            db_updated: 'Database updated.',
            downloading_entries: 'Downloading entries',
            all_entries_downloaded: 'All Entries Downloaded.',
            unsaved_branch_entries: 'Unsaved Branch Entries',
            save_now: 'Save Now',
            incomplete_entries: 'You have incomplete entries which cannot be uploaded.',
            load_more: 'Load More',
            take: 'Take',
            pick: 'Pick',
            collected_on: 'Collected on ',
            dismiss: 'Dismiss'
        }
    },
    it: {
        labels: {
            format: 'Formato',
            clear_filters: 'Ripristina Filtri',
            invalid_value: 'Invalido',
            search: 'Cerca',
            are_you_sure: 'Sei sicuro?',
            delete: 'Elimina',
            share: 'Esporta',
            locate: 'Localizza',
            or: 'Oppure',
            check_email: 'Controlla la posta',
            enter_password: 'Inserire password per verifica',
            code_was_sent: 'Codice verifica inviato',
            account_exists: 'Account esistente',
            login_with_email: 'Login con Email',
            passwordless_teaser: 'Ti mandiamo un codice nella tua inbox',
            enter_code: 'Inserisci codice',
            send: 'Invia',
            all: 'Tutte',
            incomplete: 'Incomplete',
            has_errors: 'Errori',
            wrong_range: 'Intervallo date invalido',
            invalid_entries: 'Voci non valide',
            add_branch: 'Aggiungi Branch',
            status: 'Status',
            from: 'Da',
            to: 'A',
            reset: 'Resetta',
            show: 'Mostra',
            show_filters: 'Mostra filtri sopra la lista voci',
            hide_filters: 'Nascondi filtri',
            filters: 'Filtri',
            filter_by_title: 'Filtra per titolo',
            no_hits_found: 'Trovato niente',
            not_available: 'Non disponibile',
            name: 'Nome',
            description: 'Descrizione',
            small_description: 'Piccola descrizione',
            homepage: 'Homepage',
            project_info: 'Informazioni Progetto',
            version: 'Versione',
            advanced_settings: 'Impostazioni avanzate',
            ok: 'Si',
            download_remote_entries: 'Scarica voci remote',
            remote_entry: 'Voce remota',
            download_warning: 'Questa azione rimuove tutte le voci remote esistenti sul dispositivo per questo progetto. Continuare?',
            text_size: 'Dimensione testo',
            accessibility: 'Accessibilità',
            type_answer_here: 'Scrivi qui...',
            confirm_answer_here: 'Conferma risposta qui...',
            confirm: 'Conferma',
            help: 'Supporto',
            user_guide: 'Istruzioni',
            hi: 'Ciao',
            prev: 'Prec',
            next: 'Succ',
            quit: 'Esci',
            save: 'Salva',
            save_entry: 'Salva voce',
            quit_entry: 'Esci',
            save_branch_entry: 'Salva branch',
            quit_branch: 'Esci',
            login: 'Login',
            logout: 'Logout',
            scan: 'Scan',
            entries: 'voci',
            branch_entries: 'Voci Branch',
            update_location: 'Aggiorna posizione',
            not_located_yet: 'N/A',
            latitude: 'Latitudine',
            longitude: 'Longitudine',
            accuracy: 'Accuratezza',
            unknown_error: 'Errore sconosciuto',
            db_created: 'Epicollect5 database pronto',
            db_not_created: 'Errore creazione Epicollect5 database!',
            locating: 'Localizzando',
            wait: 'Aspetta...',
            saving: 'Salvando...',
            loading: 'Caricando...',
            acquiring_position: 'Cercando posizione...',
            location_acquired: 'Posizione acquisita',
            location_fail: 'Incapace di localizzare!',
            location_service_fail: 'Geolocalizzazione e Permessi devono essere abilitati per Epicollect5 al fine di localizzare il dispositivo',
            ios_location_permission_denied: 'Epicollect5 permesso di localizzazione negato, abilitarlo nelle impostazioni',
            ios_location_permission_restricted: 'Epicollect5 permesso di localizzazione solo per utente corrente',
            android_location_permission_denied_always: 'Epicollect5 permesso geolocalizzazione negato, per favore garantirlo. Non èpossible usare geolocalizzazione senza il permesso appropriato',
            no_projects_found: 'Nesun progetto trovato',
            date_selected_is: 'Data selezionata: ',
            time_selected_is: 'Ora selezionata: ',
            preparing_scanner: 'Preparazione scanner...',
            failed_because: 'Fallito perchè: ',
            stop: 'Stop',
            play: 'Play',
            record: 'Record',
            recording: 'Registrando',
            playing: 'Playing',
            recording_audio: 'Registrando audio...',
            playing_audio: 'Playing audio...',
            shoot: 'Riprendi',
            video_saved: 'Video salvato',
            audio_saved: 'Audio salvato',
            cannot_save_file: 'Non si è potuto salvare il file! Riprovare',
            file_available: 'File disponibile',
            uploading_entries: 'Carica voci',
            loading_project: 'Caricando progetto',
            loading_entries: 'Caricando voci',
            loading_entry: 'Caricando voce',
            no_entries_found: 'Nessuna voce trovata',
            no_errors_found: 'Nessun errore',
            pick_possible_answer: 'Scegli possible risposta',
            permission_denied: 'Permesso negato',
            location_not_available: 'Gelocalizzazione non disponibile, Epicollect5 non può  localizzarti.',
            min: 'Min',
            max: 'Max',
            no_answer_given: 'Nessuna risposta fornita ',
            error: 'Errore',
            delete_project: 'Elimina progetto',
            delete_entry: 'Elimina voce',
            delete_all_entries: 'Elimina tutte le voci ',
            delete_synced_entries: 'Elimina voci sincronizzate',
            delete_unsynced_entries: 'Elimina voci non sincronizzate',
            bookmark: 'Segnalibro',
            bookmark_title: 'Aggiungi titolo per segnalibro',
            close: 'Chiudi',
            add_bookmark: 'Aggiungi segnalibro',
            add_entry: 'Aggiungi voce',
            type_hint: 'Scrivi qui',
            menu: 'Menu',
            project_options: 'Opzioni progetto',
            upload_entries: 'Carica voci',
            download_entries: 'Scarica voci',
            unsync_all_entries: 'De-sync tutte le voci',
            export_all_entries: 'Exporta tutte le voci',
            unsync_entry: 'De-sync voce',
            unsynced: 'De-sync completato',
            bookmark_page: 'Aggiungi ai segnalibri',
            remove_bookmark: 'Rimuovi dai segnalibri',
            sort: 'Ordina',
            newest: 'Dal più nuovo',
            oldest: 'Dal più vecchio',
            sign_in: 'Entrando',
            no_bookmarks_found: 'Nessun segnalibro trovato',
            my_bookmarks: 'Segnalibri',
            export_entries: 'Esporta voci in formato json',
            exporting: 'Esportando',
            exporting_success: 'Tutte le voci esportate!',
            exported_to: 'Esportate in: ',
            deleting_project: 'Elimina progetto',
            deleting_entries: 'Elimina voci',
            entry_deleted: 'Voce cancellata',
            file_deleted: 'File cancellato',
            email: 'Email',
            password: 'Password',
            ldap_username: 'Ldap Username',
            ldap_password: 'Ldap Password',
            google_sign_in: 'Google Sign In',
            upload_data: 'Carica dati',
            upload_photos: 'Carica foto',
            upload_videos: 'Carica video',
            upload_audios: 'Carica audio',
            uploading_photos: 'Caricando foto',
            uploading_videos: 'Caricando video',
            uploading_audios: 'Caricando audio',
            all_entries_uploaded: 'Tutte le voci caricate',
            entries_errors: 'Alcune voci hanno errori',
            children: 'Figli',
            search_for_project: 'Cerca progetto',
            add_project: 'Aggiungi progetto',
            projects: 'Progetti',
            delete_branch_entry: 'Elimina voce branch',
            back: 'Indietro',
            settings: 'Impostazioni',
            server_url: 'URL del server',
            server_url_placeholder: 'ex. http://www.mydomain.com',
            downloads: 'Downloads',
            download: 'Scarica',
            warning: 'Attenzione',
            missing_permission: 'Devi concedere il permesso di compiere questa azione',
            please_wait: 'Aspetta...',
            server_url_error: 'Server non trovato, controlla il server URL nelle impostazioni',
            quitting: 'Uscendo',
            cancel: 'Cancella',
            project_outdated: 'Modulo aggiornato.',
            update_project: 'Aggiorna modulo sul tuo dispositivo?',
            project_updated: 'Moduli aggiornato.',
            updating_project: 'Aggiornando moduli.',
            updating_entries: 'Aggiornando voci.',
            check_for_updates: 'Controllo per aggiornamento moduli...',
            checking_for_updates: 'Controllo per aggiornamenti...',
            loading_projects: 'Caricando progetti',
            incomplete_entry: 'Questa voce è incompleta',
            unsynced_entries: 'Voci non sincronizzate',
            unsynced_entry: 'Voce non sincronizzata',
            sync_now: 'Upload',
            save_entry_and_sync: 'Salva voce e sync',
            check_entries: 'Controlla voci',
            connect_to_internet_to_upload: 'Connessione internet richiesta per caricare voci',
            entries_errors_page: 'Voci con errori',
            check_entries_below: 'Controlla voci per errori',
            branch: 'Branch',
            pattern: 'Pattern',
            required: '* campo obbligatorio',
            entries_media_errors: 'Non è possibile caricre media. Rirpova più tardi.',
            db_updated: 'Database aggiornato.',
            downloading_entries: 'Scaricando voci',
            all_entries_downloaded: 'Tutte le voci scaricate',
            unsaved_branch_entries: 'Voci BRANCH non salvate',
            save_now: 'Salva ora',
            incomplete_entries: 'Ci sono voci incomplete che non possono essere caricate',
            load_more: 'Mostra di più',
            take: 'Camera',
            pick: 'Galleria',
            collected_on: 'Aggiunta il ',
            dismiss: 'Chiudi'
        }
    },
    es: {
        labels: {
            format: 'Formato',
            clear_filters: 'Reiniciar Filtros',
            invalid_value: 'No válido',
            search: 'Buscar',
            are_you_sure: '¿Estás seguro?',
            delete: 'Eliminar',
            share: 'Exportar',
            locate: 'Localizar',
            or: 'O',
            check_email: 'Consultar su email',
            enter_password: 'Ingrese la password para la verificación',
            code_was_sent: 'Se envió un código para verificación',
            account_exists: 'Account ya existe',
            login_with_email: 'Iniciar sesión con email',
            passwordless_teaser: 'Le enviaremos un código',
            enter_code: 'Introduzca el código',
            send: 'Enviar',
            all: 'Todos',
            incomplete: 'Incompleta',
            has_errors: 'Error',
            wrong_range: 'Intervalo incorrecto',
            invalid_entries: 'Entradas inválidas',
            add_branch: 'Añadir Branch',
            status: 'Status',
            from: 'Desde',
            to: 'A',
            reset: 'Reiniciar',
            show: 'Mostrar',
            show_filters: 'Mostrar filtros en la lista de entradas',
            hide_filters: 'Ocultar filtros',
            filters: 'Filtros',
            filter_by_title: 'Filtrar por título',
            no_hits_found: 'No se encontró nada',
            not_available: 'No disponible',
            name: 'Nombre',
            description: 'Descripción',
            small_description: 'Pequeña descripción',
            homepage: 'Página principal',
            project_info: 'Información del proyecto',
            version: 'Versión',
            advanced_settings: 'Avanzado',
            ok: 'Ok',
            download_remote_entries: 'Descargar entradas remotas',
            remote_entry: 'Entrada remota',
            download_warning: 'Esto eliminará cualquier entrada remota que ya tengas para este proyecto en tu dispositivo. ¿Continuar?',
            text_size: 'Tamaño del texto',
            accessibility: 'Accesibilidad',
            type_answer_here: 'Escriba la respuesta aquí...',
            confirm_answer_here: 'Confirmar la respuesta aquí...',
            confirm: 'Confirmar',
            help: 'Auxilio',
            user_guide: 'Instrucciones',
            hi: 'Hola',
            prev: 'Prev',
            next: 'Próx',
            quit: 'Abandonar',
            save: 'Guardar',
            save_entry: 'Guardar entrada',
            quit_entry: 'Abandonar entrada',
            save_branch_entry: 'Guardar branch',
            quit_branch: 'Abandonar',
            login: 'Iniciar sesión',
            logout: 'Cerrar sesión',
            scan: 'Escanear',
            entries: 'entradas',
            branch_entries: 'Branch entradas',
            update_location: 'Actualizar ubicación',
            not_located_yet: 'N/D',
            latitude: 'Latitud',
            longitude: 'Longitud',
            accuracy: 'Precisión',
            unknown_error: 'Error desconocido',
            db_created: 'Base de datos Epicollect5 creada',
            db_not_created: 'Error al crear la bases de datos Epicollect5!',
            locating: 'Localización',
            wait: 'Espere...',
            saving: 'Guardando...',
            loading: 'Cargando...',
            acquiring_position: 'Adquirir la ubicación...',
            location_acquired: 'Ubicación adquirida',
            location_fail: 'No se pudo localizar!',
            location_service_fail: 'La geolocalización y permisos deben estar habilitadas para Epicollect5 con el fin de localizar su dispositivo',
            ios_location_permission_denied: 'Epicollect5 negó el permiso de localización, que permite en la configuración',
            ios_location_permission_restricted: 'Epicollect5 localización permite solamente al usuario actual',
            android_location_permission_denied_always: 'Epicollect5 localización negó el permiso, por favor provea. No es posible usar geolocalización sin la autorización correspondiente',
            no_projects_found: 'No se encontraron proyectos',
            date_selected_is: 'Fecha seleccionada: ',
            time_selected_is: 'Hora seleccionada: ',
            preparing_scanner: 'Preparación del escáner...',
            failed_because: 'Falló porque: ',
            stop: 'Detener',
            play: 'Reproducir',
            record: 'Grabar',
            recording: 'Grabando',
            playing: 'Reproduciendo',
            recording_audio: 'Grabando audio...',
            playing_audio: 'Reproduciendo audio...',
            shoot: 'Grabar',
            video_saved: 'Video guardado',
            audio_saved: 'Audio guardado',
            cannot_save_file: 'Archivo no guardado! Inténtelo de nuevo',
            file_available: 'Archivo disponible',
            uploading_entries: 'Cargar entradas',
            loading_project: 'Cargar proyecto',
            loading_entries: 'Cargando entradas',
            loading_entry: 'Cargando entrada',
            no_entries_found: 'No encontradas',
            no_errors_found: 'No hay error',
            pick_possible_answer: 'Elige la respuesta posible',
            permission_denied: 'Permiso denegado',
            location_not_available: 'La geolocalización no se encuentra disponible, Epicollect5 no puede localizarte.',
            min: 'Min',
            max: 'Max',
            no_answer_given: 'Ninguna respuesta proveída ',
            error: 'Error',
            delete_project: 'Eliminar proyecto',
            delete_entry: 'Eliminar entrada',
            delete_all_entries: 'Eliminar todas las entradas ',
            delete_synced_entries: 'Eliminar entradas sincronizadas',
            delete_unsynced_entries: 'Eliminar entradas no sincronizadas',
            bookmark: 'Marcador',
            bookmark_title: 'Título del marcador',
            close: 'Cerrar',
            add_bookmark: 'Añadir marcador',
            add_entry: 'Añadir entrada',
            type_hint: 'Escriba aquí',
            menu: 'Menú',
            project_options: 'Opciones del proyecto',
            upload_entries: 'Subir entradas',
            download_entries: 'Descargar entradas',
            unsync_all_entries: 'Desincronizar entradas',
            export_all_entries: 'Exportar entradas',
            unsync_entry: 'Desincronizar entrada',
            unsynced: 'Entradas desincronizadas',
            bookmark_page: 'Marca esta pagina',
            remove_bookmark: 'Eliminar marcador',
            sort: 'Orden',
            newest: 'El más nuevo',
            oldest: 'El más antiguo',
            sign_in: 'Iniciar',
            no_bookmarks_found: 'Ningún marcadores',
            my_bookmarks: 'Marcadores',
            export_entries: 'Exportar entradas',
            exporting: 'Exportando',
            exporting_success: 'Todas las entradas exportadas!',
            exported_to: 'Exportado a: ',
            deleting_project: 'Eliminando proyecto',
            deleting_entries: 'Eliminando entradas',
            entry_deleted: 'Entrada suprimida',
            file_deleted: 'File suprimido',
            email: 'Email',
            password: 'Password',
            ldap_username: 'Ldap Username',
            ldap_password: 'Ldap Password',
            google_sign_in: 'Google Sign In',
            upload_data: 'Subir datos',
            upload_photos: 'Subir fotos',
            upload_videos: 'Subir videos',
            upload_audios: 'Subir audios',
            uploading_photos: 'Subiendo fotos',
            uploading_videos: 'Subiendo videos',
            uploading_audios: 'Subiendo audios',
            all_entries_uploaded: 'Todas las entradas subidas',
            entries_errors: 'Algunas entradas tienen errores',
            children: 'Niños',
            search_for_project: 'Buscar proyecto',
            add_project: 'Añadir proyecto',
            projects: 'Proyectos',
            delete_branch_entry: 'Eliminar entrada branch',
            back: 'Regresar',
            settings: 'Configuración',
            server_url: 'URL del servidor',
            server_url_placeholder: 'ej. http://www.mydomain.com',
            downloads: 'Descargas',
            download: 'Descarga',
            warning: 'Advertencia',
            missing_permission: 'Necesitas permiso para realizar esta acción',
            please_wait: 'Espere...',
            server_url_error: 'Servidor no encontrado. Compruebe la URL del servidor en la configuración',
            quitting: 'Abandonando',
            cancel: 'Cancelar',
            project_outdated: 'formulario desactualizado.',
            update_project: 'Actualizar proyecto en el dispositivo?',
            project_updated: 'Formularios actualizados.',
            updating_project: 'Actualizando de formularios...',
            updating_entries: 'Actualizando de entradas.',
            check_for_updates: 'Buscar actualizaciones de formularios...',
            checking_for_updates: 'Buscando actualizaciones...',
            loading_projects: 'Cargando proyectos',
            incomplete_entry: 'Entrada incompleta',
            unsynced_entries: 'Entradas no sincronizadas',
            unsynced_entry: 'Entrada no sincronizada',
            sync_now: 'Sincronizar',
            save_entry_and_sync: 'Guardar entrada y sincronizar',
            check_entries: 'Comprobar entradas',
            connect_to_internet_to_upload: 'Se requiere conexión a Internet',
            entries_errors_page: 'Entradas con errores',
            check_entries_below: 'Compruebe las entradas de los errores',
            branch: 'Branch',
            pattern: 'Pattern',
            required: '* Requerido',
            entries_media_errors: 'Error al cargar medios. Intenta más tarde',
            db_updated: 'Base de datos actualizada',
            downloading_entries: 'Descarga de entradas',
            all_entries_downloaded: 'Todas las entradas descargadas',
            unsaved_branch_entries: 'Entradas BRANCH no guardadas',
            save_now: 'Guardar ahora',
            incomplete_entries: 'Las entradas incompletas no se pueden cargar',
            load_more: 'Mostrar más',
            take: 'Cámara',
            pick: 'Galería',
            collected_on: 'Recogida en ',
            dismiss: 'Cerrar'
        }
    },
    fr: {
        labels: {
            format: 'Format',
            clear_filters: 'Effacer filtres',
            invalid_value: 'Valeur invalide',
            search: 'Chercher',
            are_you_sure: 'Es-tu sûr?',
            delete: 'Supprimer',
            share: 'Exporter',
            locate: 'Localiser',
            or: 'Ou',
            check_email: 'Vérifiez votre email',
            enter_password: 'Veuillez saisir password pour vérification',
            code_was_sent: 'Un code a été envoyé pour vérification',
            account_exists: 'Account existe déjà',
            login_with_email: 'Se connecter par e-maill',
            passwordless_teaser: 'Nous vous enverrons un code',
            enter_code: 'Entrez le code',
            send: 'Envoyer',
            all: 'Toute',
            incomplete: 'Incomplète',
            has_errors: 'Erreur',
            wrong_range: 'Intervalle incorrect',
            invalid_entries: 'Entrées invalides',
            add_branch: 'Ajouter Branch',
            status: 'Status',
            from: 'De',
            to: 'À',
            reset: 'Réinitialiser',
            show: 'Afficher',
            show_filters: 'Afficher les filtres',
            hide_filters: 'Masquer les filtres',
            filters: 'Filtres',
            filter_by_title: 'Filtrer par titre',
            no_hits_found: 'Rien n\'a été trouvé',
            not_available: 'Indisponible',
            name: 'Prénom',
            description: 'Description',
            small_description: 'Petite description',
            homepage: 'Homepage',
            project_info: 'Informations sur le projet',
            version: 'Version',
            advanced_settings: 'Avancé',
            ok: 'Ok',
            download_remote_entries: 'Télécharger les entrées distantes',
            remote_entry: 'Entrée à distance',
            download_warning: 'Ceci remplacera les données déjà téléchargées pour ce projet sur votre mobile. Continuer?',
            text_size: 'Taille du texte',
            accessibility: 'Accessibilité',
            type_answer_here: 'Tapez la réponse ici...',
            confirm_answer_here: 'Confirmer la réponse ici...',
            confirm: 'Confirmer',
            help: 'Aidez-moi',
            user_guide: 'Mode d\'emploi',
            hi: 'Salut',
            prev: 'Retour',
            next: 'Suite',
            quit: 'Quitter',
            save: 'Enr',
            save_entry: 'Enregistrer',
            quit_entry: 'Quitter',
            save_branch_entry: 'Enregistrer branch',
            quit_branch: 'Quitter',
            login: 'Se connecter',
            logout: 'Se déconnecter',
            scan: 'Scanner',
            entries: 'entrées',
            branch_entries: 'Branch entrées',
            update_location: 'Actualiser la position',
            not_located_yet: 'Pas encore réglé',
            latitude: 'Latitude',
            longitude: 'Longitude',
            accuracy: 'Précision',
            unknown_error: 'Erreur inconnue',
            db_created: 'Base de données Epicollect5 prête',
            db_not_created: 'Erreur de création de base de données Epicollect5!',
            locating: 'Localisation',
            wait: 'Patientez svp...',
            saving: 'Sauvegarde...',
            loading: 'Chargement...',
            acquiring_position: 'Acquisition de la position',
            location_acquired: 'Localisation acquise',
            location_fail: 'Impossible de localiser!',
            location_service_fail: 'Les services de localisation et les autorisations doivent tous deux être activés pour que Epicollect5 obtienne la localisation de l\'appareil.',
            ios_location_permission_denied: 'L\'autorisation de localisation d\'Epicollect5 a été refusée, veuillez l\'activer dans les Réglages',
            ios_location_permission_restricted: 'L\'autorisation de localisation Epicollect5 est limitée pour l\'utilisateur actuel',
            android_location_permission_denied_always: 'L\'autorisation de localisation Epicollect5 est refusée, veuillez l\'accorder. Il n\'est pas possible d\'utiliser les services de localisation sans l\'autorisation appropriée',
            no_projects_found: 'Aucun projet trouvé',
            date_selected_is: 'La date choisie est: ',
            time_selected_is: 'L\'heure choisie est: ',
            preparing_scanner: 'Préparation du scanner',
            failed_because: 'Cause de l\'échec: ',
            stop: 'Stop',
            play: 'Lecture',
            record: 'Enregistrer',
            recording: 'Enregistrement',
            playing: 'Lecture',
            recording_audio: 'Enregistrement audio...',
            playing_audio: 'Lecture audio...',
            shoot: 'Shoot',
            video_saved: 'Vidéo enregistrée',
            audio_saved: 'Audio enregistrée',
            cannot_save_file: 'Impossible d\'enregistrer le fichier! Réessayez',
            file_available: 'Fichier disponible',
            uploading_entries: 'Envoi des entrées',
            loading_project: 'Chargement du projet',
            loading_entries: 'Chargement des entrées',
            loading_entry: 'Chargement de l\'entrée',
            no_entries_found: 'Aucune entrée trouvée',
            no_errors_found: 'Pas d\'erreur',
            pick_possible_answer: 'Choisir une réponse possible',
            permission_denied: 'Permission refusée',
            location_not_available: 'La localisation n\'est pas disponible, Epicollect5 ne pourra pas vous localiser.',
            min: 'Min',
            max: 'Max',
            no_answer_given: 'Pas de réponse donnée ',
            error: 'Erreur',
            delete_project: 'Supprimer le projet',
            delete_entry: 'Supprimer l\'entrée',
            delete_all_entries: 'Supprimer toutes les entrées',
            delete_synced_entries: 'Supprimer les entrées synchronisées',
            delete_unsynced_entries: 'Supprimer les entrées non synchronisées',
            bookmark: 'Signet',
            bookmark_title: 'Ajouter un titre de signet',
            close: 'Fermer',
            add_bookmark: 'Ajouter un signet',
            add_entry: 'Ajouter une entrée',
            type_hint: 'Ecrire ici',
            menu: 'Menu',
            project_options: 'Options de Projet',
            upload_entries: 'Envoyer les entrées',
            download_entries: 'Télécharger les entrées',
            unsync_all_entries: 'Désinstaller toutes les entrées',
            unsync_entry: 'Désynchroniser les entrées',
            unsynced: 'Toutes les entrées desynchronisées',
            bookmark_page: 'Créer un signet',
            remove_bookmark: 'Retirer le signet',
            sort: 'Ordonner',
            newest: 'Le plus récent',
            oldest: 'Le plus ancien',
            sign_in: 'Connectez-vous',
            no_bookmarks_found: 'Aucun signé trouvé',
            my_bookmarks: 'Mes signets',
            export_entries: 'Exporter les entrées json',
            exporting: 'Export en cours',
            exporting_success: 'Toutes les entrées exportées!',
            exported_to: 'Exporté vers: ',
            deleting_project: 'Suppression du projet',
            deleting_entries: 'Suppression des entrées',
            entry_deleted: 'Entrée supprimée',
            file_deleted: 'File supprimée',
            email: 'Email',
            password: 'Mot de passe',
            ldap_username: 'Nom Ldap',
            ldap_password: 'Mot de passe Ldap',
            google_sign_in: 'Connexion Google',
            upload_data: 'Envoyer les données',
            upload_photos: 'Envoyer les photos',
            upload_videos: 'Envoyer les vidéos',
            upload_audios: 'Envoyer les sons',
            uploading_photos: 'Envoi de photos',
            uploading_videos: 'Envoi de vidéos',
            uploading_audios: 'Envoi de son',
            all_entries_uploaded: 'Toutes les entrées envoyées',
            entries_errors: 'Certaines entrées ont des erreurs',
            children: 'Enfants',
            search_for_project: 'Chercher un projet',
            add_project: 'Ajout Projet',
            projects: 'Projets',
            delete_branch_entry: 'Supprimer l\'entrée de branche',
            back: 'Retour',
            settings: 'Réglages',
            server_url: 'Url du serveur',
            server_url_placeholder: 'ex http://www.mydomain.com',
            downloads: 'Téléchargements',
            download: 'Téléchargement',
            warning: 'Avertissement',
            missing_permission: 'Vous devez accorder l\'autorisation appropriée pour effectuer cette action',
            please_wait: 'SVP attendez...',
            server_url_error: 'Serveur non trouvé, vérifiez l\'URL de votre serveur dans les réglages',
            quitting: 'Sortie',
            cancel: 'Annuler',
            project_outdated: 'Le formulaire a été mis à jour.',
            update_project: 'Mettre à jour le formulaire sur votre mobile?',
            project_updated: 'Formulaires mis à jour.',
            updating_project: 'Mise à jour des formulaires.',
            updating_entries: 'Mise à jour des entrées.',
            check_for_updates: 'Recherche de mises à jour de formulaires',
            checking_for_updates: 'Recherche de mises à jour...',
            loading_projects: 'Chargement de Projets',
            incomplete_entry: 'Cette entrée est incomplète',
            unsynced_entries: 'Entrées NON synchronisées',
            unsynced_entry: 'entrée NON synchronisée.',
            sync_now: 'Synchroniser',
            save_entry_and_sync: 'Sauvegarder l\'entrée et Synchroniser',
            check_entries: 'Vérifier les entrées',
            connect_to_internet_to_upload: 'SVP connectez-vous à internet pour envoyer les entrées.',
            entries_errors_page: 'Entrées avec Erreurs',
            check_entries_below: 'Vérifier les entrées ci-dessous.',
            branch: 'Branche',
            pattern: 'Modèle',
            required: '* Ce champ est requis',
            entries_media_errors: 'Impossible d\'envoyer les médias. SVP veuillez réessayer plus tard.',
            db_updated: 'Base de données mise à jour.',
            downloading_entries: 'Téléchargement des entrées',
            all_entries_downloaded: 'Toutes les entrées téléchargées.',
            unsaved_branch_entries: 'Entrées de branche non sauvées.',
            save_now: 'Sauvegarder',
            incomplete_entries: 'Vous avez des entrées incomplètes qui ne peuvent être envoyées.',
            load_more: 'Charger Plus',
            take: 'Prendre',
            pick: 'Choisir',
            collected_on: 'Collectée le ',
            dismiss: 'Annuler'
        }
    },
    pl: {
        labels: {
            format: 'Format',
            clear_filters: 'Wyczyść filtry',
            invalid_value: 'Niewłaściwa wartość',
            search: 'Szukaj',
            are_you_sure: 'Jesteś pewny?',
            delete: 'Skasuj',
            share: 'Exportuj',
            locate: 'Lokalizować',
            or: 'lub',
            check_email: 'Sprawdź swój email',
            enter_password: 'Wprowadź hasło w celu weryfikacji',
            code_was_sent: 'Kod został wysłany do weryfikacji',
            account_exists: 'Account już istnieje',
            login_with_email: 'Zaloguj się za pomocą e-maila',
            passwordless_teaser: 'Wyślemy ci kod do skrzynki odbiorczej',
            enter_code: 'Wprowadź kod',
            send: 'Wysłać',
            all: 'Wszystko',
            incomplete: 'Niekompletny',
            has_errors: 'Błąd',
            wrong_range: 'Niepoprawny odstęp',
            invalid_entries: 'Nieprawidłowe wpisy',
            add_branch: 'Dodaj Branch',
            status: 'Status',
            from: 'From',
            to: 'To',
            reset: 'Reset',
            show: 'Pokaż',
            show_filters: 'Pokaż filtry na liście wpisów',
            hide_filters: 'Ukryj filtry',
            filters: 'Filtry',
            filter_by_title: 'Filtruj według tytułu',
            no_hits_found: 'Nic nie znaleziono',
            not_available: 'niedostępne',
            name: 'Nazwa',
            description: 'Opis',
            small_description: 'Mały opis',
            homepage: 'Strona główna',
            project_info: 'Informacje o projekcie',
            version: 'Wersja',
            advanced_settings: 'Zaawansowane Ustawienia',
            ok: 'Ok',
            download_remote_entries: 'Pobierz zdalne wpisy',
            remote_entry: 'Zdalne wejść',
            download_warning: 'To spowoduje usunięcie wszystkich zdalnych wpisów, które już masz na swoim urządzeniu dla tego projektu . Kontynuować?',
            text_size: 'Rozmiar tekstu',
            accessibility: 'Dostępność',
            type_answer_here: 'Wpisz odpowiedź tutaj...',
            confirm_answer_here: 'Potwierdź odpowiedź tutaj...',
            confirm: 'Potwierdź',
            help: 'Pomoc',
            user_guide: 'Podręcznik',
            hi: 'Cześć',
            prev: 'Poprzedni',
            next: 'Następny',
            quit: 'Zrezygnuj',
            save: 'Zapisz',
            save_entry: 'Zapisz wpis',
            quit_entry: 'Zrezygnuj',
            save_branch_entry: 'Zapisz branch',
            quit_branch: 'Zrezygnuj',
            login: 'Zaloguj',
            logout: 'Wyloguj',
            scan: 'Skanuj',
            entries: 'wpisy',
            branch_entries: 'Grupa wpisy',
            update_location: 'Pobierz lokalizację',
            not_located_yet: 'Brak lokalizacji',
            latitude: 'Szerokość',
            longitude: 'Długość',
            accuracy: 'Dokładność',
            unknown_error: 'Nieznany błąd',
            db_created: 'Epicollect5 baza danych gotowa',
            db_not_created: 'Błąd tworzenia bazy danych Epicollect5!',
            locating: 'Lokalizowanie',
            wait: 'Proszę czekać...',
            saving: 'Zapisywanie...',
            loading: 'Ładowanie...',
            acquiring_position: 'Ustalanie pozycji',
            location_acquired: 'Pozycja ustalona',
            location_fail: 'Nie mogę zlokalizować!',
            location_service_fail: 'Aby pobrać położenie Epicollect5 musi mieć przyznane zgody na użycie usługi lokalizacji.',
            ios_location_permission_denied: 'Epicollect5 nie ma dostępu do usługi lokalizacji, prosze zmienić w Ustawieniach',
            ios_location_permission_restricted: 'Epicollect5 ma ograniczony dostęp do usługi lokalizacji jedynie dla obecnego użytkownika',
            android_location_permission_denied_always: 'Epicollect5 nie ma dostępu do usługi lokalizacji. Nie można używać lokalizacji bez nadania odpowiednich uprawnień dla aplikacji',
            no_projects_found: 'Nie znaleziono projektu',
            date_selected_is: 'Wybrana data to: ',
            time_selected_is: 'Wybrany czas to: ',
            preparing_scanner: 'Przygotowanie skanera',
            failed_because: 'Niepowodzenie ponieważ: ',
            stop: 'Stop',
            play: 'Odtwórz',
            record: 'Nagraj',
            recording: 'Nagrywanie',
            playing: 'Odtwarzanie',
            recording_audio: 'Nagrywanie dźwięku...',
            playing_audio: 'Odtwarzanie dźwięku...',
            shoot: 'Migawka',
            video_saved: 'Video zapisane',
            audio_saved: 'Audio zapisane',
            cannot_save_file: 'Nie można zapisać pliku! Proszę powtórz',
            file_available: 'Plik dostępny',
            uploading_entries: 'Przesyłanie wpisów',
            loading_project: 'Ładowanie projektu',
            loading_entries: 'Ładowanie wpisów',
            loading_entry: 'Ładowanie wpisu',
            no_entries_found: 'Brak wpisów',
            no_errors_found: 'Nie znaleziono błędów',
            pick_possible_answer: 'Wybierz odpowiedź',
            permission_denied: 'Brak dostępu',
            location_not_available: 'Lokalizacja jest niedostępna Epicollect5 nie jest w stanie Cię zlokalizować.',
            min: 'Min',
            max: 'Max',
            no_answer_given: 'Nie udzielono odpowiedzi ',
            error: 'Błąd',
            delete_project: 'Skasuj projekt',
            delete_entry: 'Skasuj wpis',
            delete_all_entries: 'Skasuj wszystkie wpisy',
            delete_synced_entries: 'Skasuj przesłane wpisy',
            delete_unsynced_entries: 'Skasuj nieprzesłane wpisy',
            bookmark: 'Zakładka',
            bookmark_title: 'Dodaj tytuł zakładki',
            close: 'Zamknij',
            add_bookmark: 'Dodaj zakładkę',
            add_entry: 'Dodaj wpis',
            type_hint: 'Wpisz tutaj',
            menu: 'Menu',
            project_options: 'Opcje projektu',
            upload_entries: 'Prześlij wpisy',
            download_entries: 'Pobierz wpisy',
            unsync_all_entries: 'Unsync All Entries',
            unsync_entry: 'Unsync entry',
            unsynced: 'Unsynced All Entries',
            bookmark_page: 'Strona zakładek',
            remove_bookmark: 'Usuń zakładki',
            sort: 'Kolejność',
            newest: 'Najnowsze',
            oldest: 'Najstarsze',
            sign_in: 'Zaloguj',
            no_bookmarks_found: 'Brak zakładek',
            my_bookmarks: 'Moje zakładki',
            export_entries: 'Exportuj wpisy jako JSON',
            exporting: 'Eksportowanie',
            exporting_success: 'Wszystkie wpisy wyeksportowane!',
            exported_to: 'Exportuj do: ',
            deleting_project: 'Kasowanie projektu',
            deleting_entries: 'Kasowanie wpisu',
            entry_deleted: 'Wpis usunięty',
            file_deleted: 'File usunięty',
            email: 'Email',
            password: 'Hasło',
            ldap_username: 'Ldap Login',
            ldap_password: 'Ldap Hasło',
            google_sign_in: 'Zaloguj kontem Google',
            upload_data: 'Wyślij dane',
            upload_photos: 'Wyślij zdjęcia',
            upload_videos: 'Wyślij video',
            upload_audios: 'Wyślij audio',
            uploading_photos: 'Wysyłanie zdjęć',
            uploading_videos: 'Wysyłanie video',
            uploading_audios: 'Wysyłanie audio',
            all_entries_uploaded: 'Wszystkie wpisy wysłane',
            entries_errors: 'Niektóre wpisy zawierają błędy',
            children: 'Dziecko',
            search_for_project: 'Szukaj projektu',
            add_project: 'Dodaj projekt',
            projects: 'Projekty',
            delete_branch_entry: 'Usuń grupę wpisów',
            back: 'Powrót',
            settings: 'Ustawienia',
            server_url: 'Adres serwera',
            server_url_placeholder: 'np. http://www.mydomain.com',
            downloads: 'Pobrania',
            download: 'Pobierz',
            warning: 'Uwaga',
            missing_permission: 'Aby wykonać to działanie musisz nadać odpowiednie uprawnienia.',
            please_wait: 'Proszę czekać...',
            server_url_error: 'Nie znaleziono serwera, sprawdź w ustawieniach adres serwera',
            quitting: 'Anulowanie',
            cancel: 'Anuluj',
            project_outdated: 'Formularz zaktualizowany.',
            update_project: 'Czy zaktualizować formularz na Twoim urządzeniu?',
            project_updated: 'Formularze zaktualizowane.',
            updating_project: 'Aktualizacja formularzy.',
            updating_entries: 'Aktualizacja wpisów.',
            check_for_updates: 'Poszukaj aktualizację formularza',
            checking_for_updates: 'Szukam aktualizacji...',
            loading_projects: 'Wgrywanie projektów',
            incomplete_entry: 'Wpis jest niekompletny',
            unsynced_entries: 'Wpisy do przesłania',
            unsynced_entry: 'Wpis wymaga przesłania.',
            sync_now: 'Prześlij',
            save_entry_and_sync: 'Zapisz wpis i wyślij',
            check_entries: 'Sprawdź wpisy',
            connect_to_internet_to_upload: 'Połącz się z internetem i prześlij wpisy.',
            entries_errors_page: 'Wpisy z błędami',
            check_entries_below: 'Sprawdź błędy w poniższych wpisach.',
            branch: 'Grupa',
            pattern: 'Wzór',
            required: '* Pole wymagane',
            entries_media_errors: 'Nie udało się przesłać multimediów. Spróbuj później.',
            db_updated: 'Baza danych zaktualizowana.',
            downloading_entries: 'Pobieranie wpisów',
            all_entries_downloaded: 'Wszystkie wpisy pobrane.',
            unsaved_branch_entries: 'Nie zapisano wszystkich wpisów w grupie.',
            save_now: 'Zapisz teraz',
            incomplete_entries: 'Niektóre wpisy są niekompletne i nie mogą być przesłane.',
            load_more: 'Pokaż więcej',
            take: 'Zrób',
            pick: 'Pobierz',
            collected_on: 'Zebrane na/w ',
            dismiss: 'Anuluj'
        }
    }
};